# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 19:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 11, 19, 17, 46, 993818, tzinfo=utc)),
        ),
    ]
